/* automatikusan generált fordítás-szótár — 35 kulcs (GYIK oldal: gyik.html) */
window.UQI18N = window.UQI18N || {};
Object.assign(window.UQI18N, {

  /* ---------- FEJLÉC ---------- */
  "Gyakori kérdések": { en: "Frequently asked questions", de: "Häufige Fragen", fr: "Questions fréquentes", es: "Preguntas frecuentes", it: "Domande frequenti" },
  "Ha valamire nem találsz itt választ, írj nyugodtan:": { en: "If you can't find an answer here, just write to us:", de: "Wenn du hier keine Antwort findest, schreib uns einfach:", fr: "Si tu ne trouves pas ta réponse ici, écris-nous sans hésiter :", es: "Si no encuentras aquí tu respuesta, escríbenos sin problema:", it: "Se qui non trovi la risposta, scrivici pure:" },

  /* ---------- AZ ALAPOK ---------- */
  "Az alapok": { en: "The basics", de: "Die Grundlagen", fr: "Les bases", es: "Lo básico", it: "Le basi" },
  "Kell hozzá alkalmazást telepíteni?": { en: "Do I need to install an app?", de: "Muss ich eine App installieren?", fr: "Faut-il installer une application ?", es: "¿Hay que instalar una aplicación?", it: "Serve installare un'app?" },
  "Nem. Az Urban Quest a böngészőben fut — elég megnyitni ezt az oldalt a telefonodon.": { en: "No. Urban Quest runs in your browser — you just open this page on your phone.", de: "Nein. Urban Quest läuft im Browser — du musst diese Seite nur auf deinem Handy öffnen.", fr: "Non. Urban Quest fonctionne dans le navigateur — il suffit d'ouvrir cette page sur ton téléphone.", es: "No. Urban Quest funciona en el navegador: basta con abrir esta página en tu móvil.", it: "No. Urban Quest funziona nel browser: basta aprire questa pagina sul telefono." },
  "Mennyibe kerül?": { en: "How much does it cost?", de: "Was kostet das?", fr: "Combien ça coûte ?", es: "¿Cuánto cuesta?", it: "Quanto costa?" },
  "Jelenleg minden küldetésünk ingyenes. Nincs előfizetés és nincs regisztrációs díj.": { en: "Right now all our quests are free. There's no subscription and no sign-up fee.", de: "Zurzeit sind alle unsere Missionen kostenlos. Es gibt kein Abo und keine Anmeldegebühr.", fr: "Pour l'instant, toutes nos missions sont gratuites. Pas d'abonnement, pas de frais d'inscription.", es: "Ahora mismo todas nuestras misiones son gratuitas. No hay suscripción ni cuota de registro.", it: "Al momento tutte le nostre missioni sono gratuite. Nessun abbonamento e nessuna quota d'iscrizione." },
  "Kell regisztrálni?": { en: "Do I have to sign up?", de: "Muss ich mich registrieren?", fr: "Faut-il créer un compte ?", es: "¿Hay que registrarse?", it: "Bisogna registrarsi?" },
  "Játszani regisztráció nélkül is tudsz. Fiók akkor kell, ha szeretnéd, hogy\n     megmaradjon a haladásod, és ha fel akarsz kerülni a ranglistára — vendégként\n     a végigjátszás nem mentődik el.": { en: "You can play without signing up. You only need an account if you want your progress to be kept and if you want to get onto the leaderboard — as a guest, your playthrough isn't saved.", de: "Spielen kannst du auch ohne Registrierung. Ein Konto brauchst du nur, wenn dein Fortschritt erhalten bleiben soll und wenn du in die Rangliste willst — als Gast wird der Durchlauf nicht gespeichert.", fr: "Tu peux jouer sans créer de compte. Un compte n'est nécessaire que si tu veux conserver ta progression et apparaître au classement — en invité, la partie n'est pas enregistrée.", es: "Puedes jugar sin registrarte. Solo necesitas una cuenta si quieres que se guarde tu progreso y si quieres entrar en la clasificación: como invitado, la partida no se guarda.", it: "Puoi giocare anche senza registrarti. L'account serve solo se vuoi che i tuoi progressi restino e se vuoi entrare in classifica: da ospite la partita non viene salvata." },
  "Mi kell hozzá a helyszínen?": { en: "What do we need on the spot?", de: "Was brauchst du vor Ort?", fr: "Qu'est-ce qu'il faut avoir sur place ?", es: "¿Qué hay que llevar encima?", it: "Che cosa serve sul posto?" },
  "Feltöltött telefon, internetkapcsolat és kényelmes cipő. A küldetések séta-távolságra\n     tervezettek.": { en: "A charged phone, an internet connection and comfortable shoes. The quests are designed for walking distance.", de: "Ein geladenes Handy, eine Internetverbindung und bequeme Schuhe. Die Missionen sind auf Fußwege ausgelegt.", fr: "Un téléphone chargé, une connexion internet et des chaussures confortables. Les missions sont conçues pour se faire à pied.", es: "El móvil cargado, conexión a internet y zapatos cómodos. Las misiones están pensadas para recorrerse a pie.", it: "Un telefono carico, una connessione a internet e scarpe comode. Le missioni sono pensate per essere fatte a piedi." },
  "Az internetkapcsolat kell a játék közben is.": { en: "You need the internet connection during the game too.", de: "Die Internetverbindung brauchst du auch während des Spiels.", fr: "La connexion internet est nécessaire pendant le jeu aussi.", es: "La conexión a internet hace falta también durante el juego.", it: "La connessione a internet serve anche durante il gioco." },
  "A küldetés jelenleg\n       nem működik offline: ha elfogy a mobilnet, a válaszaitok nem jutnak el hozzánk,\n       amíg vissza nem tér a kapcsolat.": { en: "The quest currently doesn't work offline: if your mobile data runs out, your answers won't reach us until the connection is back.", de: "Die Mission funktioniert derzeit nicht offline: Wenn euer mobiles Internet ausgeht, kommen eure Antworten erst bei uns an, wenn die Verbindung zurück ist.", fr: "Pour le moment, la mission ne fonctionne pas hors ligne : si vous n'avez plus de données mobiles, vos réponses ne nous parviennent pas tant que la connexion n'est pas revenue.", es: "De momento la misión no funciona sin conexión: si os quedáis sin datos móviles, vuestras respuestas no nos llegan hasta que vuelva la conexión.", it: "Al momento la missione non funziona offline: se finiscono i dati mobili, le vostre risposte non ci arrivano finché la connessione non torna." },

  /* ---------- JÁTÉK KÖZBEN ---------- */
  "Játék közben": { en: "During the game", de: "Während des Spiels", fr: "Pendant le jeu", es: "Durante el juego", it: "Durante il gioco" },
  "Hányan játszhatunk?": { en: "How many of us can play?", de: "Wie viele können mitspielen?", fr: "On peut jouer à combien ?", es: "¿Cuántos podemos jugar?", it: "In quanti si può giocare?" },
  "Egyedül is mehet. Csapatban úgy játszotok, hogy egyikőtök nyit egy csapatot, és\n     megosztja a csatlakozási kódot — onnantól mindenki a saját telefonján játszik,\n     de közös menetben, közös pontszámmal.": { en: "You can go solo too. To play as a team, one of you opens a team and shares the join code — from then on everyone plays on their own phone, but in the same run, with a shared score.", de: "Allein geht es auch. Im Team spielt ihr so: Einer von euch eröffnet ein Team und teilt den Beitrittscode — ab da spielt jeder auf seinem eigenen Handy, aber in derselben Runde und mit gemeinsamer Punktzahl.", fr: "En solo, ça marche aussi. En équipe, l'un de vous crée une équipe et partage le code d'accès — ensuite chacun joue sur son propre téléphone, mais dans la même partie et avec un score commun.", es: "También se puede ir en solitario. En equipo, uno de vosotros crea un equipo y comparte el código de acceso: a partir de ahí cada uno juega en su propio móvil, pero en la misma partida y con una puntuación común.", it: "Si può andare anche da soli. In squadra, uno di voi apre una squadra e condivide il codice di accesso: da lì in poi ognuno gioca sul proprio telefono, ma nella stessa partita e con lo stesso punteggio." },
  "Meddig tart egy küldetés?": { en: "How long does a quest take?", de: "Wie lange dauert eine Mission?", fr: "Combien de temps dure une mission ?", es: "¿Cuánto dura una misión?", it: "Quanto dura una missione?" },
  "Küldetéstől függ; a várható időt és a távot minden pálya adatlapján előre látod.": { en: "It depends on the quest; you can see the expected time and the distance in advance on the info page of every course.", de: "Das hängt von der Mission ab; die voraussichtliche Dauer und die Strecke siehst du vorab auf der Infoseite jeder Strecke.", fr: "Ça dépend de la mission ; la durée prévue et la distance sont indiquées à l'avance sur la fiche de chaque parcours.", es: "Depende de la misión; el tiempo previsto y la distancia los ves de antemano en la ficha de cada recorrido.", it: "Dipende dalla missione; il tempo previsto e la distanza li vedi in anticipo nella scheda di ogni percorso." },
  "Megállhatunk közben?": { en: "Can we stop along the way?", de: "Können wir zwischendurch pausieren?", fr: "On peut faire une pause en route ?", es: "¿Podemos parar por el camino?", it: "Possiamo fermarci per strada?" },
  "Igen, nincs időre menő kényszer. Bejelentkezve a haladásotok megmarad, és később\n     onnan folytathatjátok, ahol abbahagytátok — ugyanabban a böngészőben.": { en: "Yes, nothing is racing against the clock. Logged in, your progress is kept and you can carry on later from where you left off — in the same browser.", de: "Ja, es läuft keine Uhr gegen euch. Eingeloggt bleibt euer Fortschritt erhalten, und ihr könnt später da weitermachen, wo ihr aufgehört habt — im selben Browser.", fr: "Oui, rien ne vous force à courir contre la montre. Connectés, votre progression est conservée et vous pouvez reprendre plus tard là où vous vous êtes arrêtés — dans le même navigateur.", es: "Sí, nada os obliga a correr contra el reloj. Con la sesión iniciada, vuestro progreso se conserva y podéis continuar más tarde donde lo dejasteis, en el mismo navegador.", it: "Sì, non c'è nessuna corsa contro il tempo. Con l'accesso effettuato i vostri progressi restano e potete riprendere più tardi da dove avevate lasciato, nello stesso browser." },
  "Mi történik, ha rossz választ adunk?": { en: "What happens if we give a wrong answer?", de: "Was passiert, wenn wir falsch antworten?", fr: "Que se passe-t-il si on donne une mauvaise réponse ?", es: "¿Qué pasa si damos una respuesta equivocada?", it: "Che cosa succede se sbagliamo risposta?" },
  "Semmi baj, újra próbálkozhattok. Ha elakadtok, kérhettek tippet — az viszont\n     levon a megszerezhető pontból.": { en: "No problem, you can try again. If you get stuck you can ask for a hint — but that cuts into the points you can earn.", de: "Kein Problem, ihr könnt es noch einmal versuchen. Wenn ihr feststeckt, könnt ihr einen Tipp anfordern — der zieht allerdings von den erreichbaren Punkten ab.", fr: "Pas de souci, vous pouvez réessayer. Si vous bloquez, vous pouvez demander un indice — mais il réduit les points à gagner.", es: "No pasa nada, podéis volver a intentarlo. Si os atascáis, podéis pedir una pista, pero esa resta puntos de los que podéis conseguir.", it: "Nessun problema, potete riprovare. Se vi bloccate potete chiedere un indizio, ma toglie punti da quelli che potete ottenere." },
  "Mi az a döntési pont?": { en: "What is a decision point?", de: "Was ist ein Entscheidungspunkt?", fr: "Qu'est-ce qu'un point de décision ?", es: "¿Qué es un punto de decisión?", it: "Che cos'è un punto di decisione?" },
  "Olyan állomás, ahol a válaszotok azt is eldönti, merre mentek tovább. Ilyenkor a\n     csapat két különböző útvonalon folytathatja — ugyanazt a pályát kétszer játszva\n     nem feltétlenül ugyanazt látjátok.": { en: "A station where your answer also decides which way you go next. There the team can carry on along two different routes — if you play the same course twice, you won't necessarily see the same thing.", de: "Eine Station, an der eure Antwort auch bestimmt, wie es weitergeht. Dort kann das Team auf zwei verschiedenen Routen weiterziehen — wenn ihr dieselbe Strecke zweimal spielt, seht ihr nicht unbedingt dasselbe.", fr: "Une étape où votre réponse décide aussi de la suite du parcours. L'équipe peut alors continuer par deux itinéraires différents — en jouant deux fois le même parcours, vous ne verrez pas forcément la même chose.", es: "Una estación en la que vuestra respuesta decide también por dónde seguís. Ahí el equipo puede continuar por dos rutas distintas: jugando dos veces el mismo recorrido no veréis necesariamente lo mismo.", it: "Una tappa in cui la vostra risposta decide anche da che parte proseguite. Lì la squadra può continuare su due percorsi diversi: giocando due volte lo stesso percorso non vedrete per forza le stesse cose." },

  /* ---------- PONTOK ÉS RANGLISTA ---------- */
  "Pontok és ranglista": { en: "Points and leaderboard", de: "Punkte und Rangliste", fr: "Points et classement", es: "Puntos y clasificación", it: "Punti e classifica" },
  "Hogyan számolódik a pontszám?": { en: "How is the score calculated?", de: "Wie wird die Punktzahl berechnet?", fr: "Comment le score est-il calculé ?", es: "¿Cómo se calcula la puntuación?", it: "Come viene calcolato il punteggio?" },
  "A pontokat a kiszolgáló számolja a beküldött válaszokból, nem a telefon — így\n     mindenkinél ugyanaz a mérce. A kért tippek levonódnak.": { en: "The points are worked out by the server from the answers you send in, not by your phone — so everyone is measured the same way. Hints you ask for are deducted.", de: "Die Punkte berechnet der Server aus den eingesendeten Antworten, nicht das Handy — so gilt für alle derselbe Maßstab. Angeforderte Tipps werden abgezogen.", fr: "Les points sont calculés par le serveur à partir des réponses envoyées, pas par le téléphone — la même règle vaut donc pour tout le monde. Les indices demandés sont déduits.", es: "Los puntos los calcula el servidor a partir de las respuestas enviadas, no el móvil, así que la vara de medir es la misma para todos. Las pistas pedidas se descuentan.", it: "I punti li calcola il server dalle risposte inviate, non il telefono: così il metro è lo stesso per tutti. Gli indizi richiesti vengono scalati." },
  "Miért nem látom magam a ranglistán?": { en: "Why don't I see myself on the leaderboard?", de: "Warum finde ich mich nicht in der Rangliste?", fr: "Pourquoi je n'apparais pas au classement ?", es: "¿Por qué no me veo en la clasificación?", it: "Perché non mi vedo in classifica?" },
  "A ranglistára a befejezett menetek kerülnek fel, és csak bejelentkezett fiókkal.\n     Ha vendégként játszottál, az eredmény nem őrződik meg.": { en: "Only finished runs get onto the leaderboard, and only with a logged-in account. If you played as a guest, the result isn't kept.", de: "In die Rangliste kommen nur abgeschlossene Runden, und nur mit einem eingeloggten Konto. Wenn du als Gast gespielt hast, bleibt das Ergebnis nicht erhalten.", fr: "Seules les parties terminées entrent au classement, et uniquement avec un compte connecté. Si tu as joué en invité, le résultat n'est pas conservé.", es: "A la clasificación solo llegan las partidas terminadas, y únicamente con la sesión iniciada. Si jugaste como invitado, el resultado no se conserva.", it: "In classifica entrano solo le partite completate, e solo con un account collegato. Se hai giocato da ospite, il risultato non viene conservato." },

  /* ---------- FIÓK ÉS ADATOK ---------- */
  "Fiók és adatok": { en: "Account and data", de: "Konto und Daten", fr: "Compte et données", es: "Cuenta y datos", it: "Account e dati" },
  "Törölhetem a fiókomat?": { en: "Can I delete my account?", de: "Kann ich mein Konto löschen?", fr: "Puis-je supprimer mon compte ?", es: "¿Puedo borrar mi cuenta?", it: "Posso cancellare il mio account?" },
  "Igen, a Fiókom oldalon. A törlés a hozzá tartozó adatokra is kiterjed.": { en: "Yes, on the My account page. Deleting it covers the data that belongs to it as well.", de: "Ja, auf der Seite Mein Konto. Die Löschung erstreckt sich auch auf die zugehörigen Daten.", fr: "Oui, depuis la page Mon compte. La suppression porte aussi sur les données associées.", es: "Sí, en la página Mi cuenta. El borrado incluye también los datos asociados.", it: "Sì, dalla pagina Il mio account. La cancellazione riguarda anche i dati collegati." },
  "Részletek az adatvédelmi tájékoztatóban.": { en: "Details in the Privacy Policy.", de: "Einzelheiten in der Datenschutzerklärung.", fr: "Les détails dans la politique de confidentialité.", es: "Los detalles, en la política de privacidad.", it: "I dettagli nell'informativa sulla privacy." },
  "Elfelejtettem a jelszavam.": { en: "I forgot my password.", de: "Ich habe mein Passwort vergessen.", fr: "J'ai oublié mon mot de passe.", es: "He olvidado mi contraseña.", it: "Ho dimenticato la password." },
  "A jelszó-visszaállítás jelenleg fejlesztés alatt áll. Addig írj nekünk, és segítünk:": { en: "Password reset is still under development. Until then, write to us and we'll help:", de: "Das Zurücksetzen des Passworts ist noch in Arbeit. Schreib uns bis dahin, wir helfen dir:", fr: "La réinitialisation du mot de passe est encore en développement. En attendant, écris-nous et on t'aide :", es: "El restablecimiento de la contraseña todavía está en desarrollo. Mientras tanto, escríbenos y te ayudamos:", it: "Il ripristino della password è ancora in fase di sviluppo. Nel frattempo scrivici e ti aiutiamo:" },
});
